name: Expression context
on: [push,workflow_dispatch,issues]
run-name: "Expression and context by user ${{ github.actor }} and event: ${{ github.event_name}}"
jobs:
   run-on-workflow_dispatch:
     runs-on: ubuntu-latest
     if: contains(fromJson('[push,workflow_dispatch,issues]'), 'workflow_dispatch')
     steps:
        - name: Run only if the event is workflow-dispatch
          if: contains(github.event.issue.labels.*.name, 'bug')
          run: |
             echo '${{ join(github.event.issue.labels.*.name,' ,')}}'
          
   expressions_contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
        - name: Expressions
          id: expressions
          run: |
             echo ${{ 1 }}
             echo ${{ 'This is string' }}
             echo ${{ null }}
             echo ${{ true }}
             echo ${{ 1 > 2 }}
             echo ${{ true && false }}
             echo ${{ true || (false && true) }}
        - name: context
          id: context     
          run: |
             echo '${{ toJson(github) }}'
             echo '${{ toJson(job) }}'
             echo '${{ toJson(secrets) }}'
             echo '${{ toJson(inputs) }}'
             echo '${{ toJson(steps) }}'
             echo '${{ toJson(runner) }}'

