name: simple-action
on: [push]

jobs:
  simple-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: Tushar
      - name: Print the output
        run: echo ${{ steps.greet.outputs.time }}
  checkout-actions:
      runs-on: ubuntu-latest
      steps:
        - name: Simple checkout-action
          uses: actions/checkout@v3
        - name: list after checkout
          run: ls -a

  