name: Status Check Functions
on: [push, workflow_dispatch]

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo "Step 2 has failed"
      - name: Runs on Success
        if: success()
        run: echo "Runs on Success"
      - name: Runs Always
        if: always()
        run: echo "Runs always"  
      - name: Runs on Cancellation
        if: cancelled()
        run: echo "Runs on cancellations"    
  job-2:
    runs-on: ubuntu-latest
    needs: status-check
    if: failure()
    steps:
      - run: echo "Job 2 runs"

