name: Working dirs and Shells
on: [push]
defaults:
    run:
      shell: bash  
jobs:
   working-dir-shells:
    runs-on: ubuntu-latest
    steps:
        - name: Display working dirs and list files
          run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
   working-dir-shells-windows:
    runs-on: windows-latest
    steps:     
      - name: Display working dirs and list files
        run: |
              pwd
              ls -a
              echo $GITHUB_SHA
              echo $GITHUB_REPOSITORY
              echo $GITHUB_WORKSPACE    