name: workflow-commands
on: [push]
jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Error came from workflow"
      - name: Setting error message with params
        run: echo "::error title:Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon" 
      - name: Setting debug message with params
        run: echo "::debug title:Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"  
      - name: Setting warning message with params
        run: echo "::warning title:Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting notice message with params
        run: echo "::notice title:Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"  